defmodule Mix.Tasks.Arbor.LifecycleIdentityTest do
  use ExUnit.Case, async: true

  alias Mix.Tasks.Arbor.Helpers, as: Config
  alias Mix.Tasks.Arbor.LifecycleIdentity, as: Identity
  alias Mix.Tasks.Arbor.Restart
  alias Mix.Tasks.Arbor.Start
  alias Mix.Tasks.Arbor.Status

  @local_id "045c"
  @node "arbor_dev_045c@127.0.0.1"
  @other_node "arbor_dev_045c@10.42.42.103"
  @foreign_node "arbor_dev_dead1@127.0.0.1"

  # A throwaway per-test directory so boundary tests never touch the real
  # ~/.arbor. Never used to signal anything; only ever read/written as plain
  # files, and cleaned up on exit.
  defp tmp_home do
    dir =
      Path.join(System.tmp_dir!(), "arbor_lifecycle_test_#{System.unique_integer([:positive])}")

    File.mkdir_p!(dir)
    on_exit(fn -> File.rm_rf!(dir) end)
    dir
  end

  # The test process's own OS pid: genuinely alive, and genuinely not an
  # Arbor node (its argv never matches `-name`/`-sname arbor_dev_<hex>@...`),
  # so every boundary test that reaches a real signal-authorization check
  # deterministically lands on the refused/preserve-evidence branch. No
  # test in this file ever exercises the safe-to-signal branch against a
  # real process.
  defp self_pid, do: System.pid() |> String.to_integer()

  # -- parse_metadata / encode_metadata -------------------------------------

  describe "parse_metadata/1" do
    test "accepts a well-formed record" do
      raw = Jason.encode!(%{version: 1, node: @node, host: "127.0.0.1", pid: 123, state: "ready"})

      assert {:ok, %{node: @node, host: "127.0.0.1", pid: 123, state: :ready}} =
               Identity.parse_metadata(raw)
    end

    test "rejects oversized payloads without parsing them" do
      raw =
        Jason.encode!(%{
          version: 1,
          node: @node,
          host: String.duplicate("a", 5000),
          pid: 1,
          state: "ready"
        })

      assert {:error, :malformed} = Identity.parse_metadata(raw)
    end

    test "rejects non-JSON" do
      assert {:error, :malformed} = Identity.parse_metadata("not json")
    end

    test "rejects wrong version" do
      raw = Jason.encode!(%{version: 2, node: @node, host: "127.0.0.1", pid: 1, state: "ready"})
      assert {:error, :malformed} = Identity.parse_metadata(raw)
    end

    test "rejects malformed node shape" do
      raw =
        Jason.encode!(%{
          version: 1,
          node: "not-a-node",
          host: "127.0.0.1",
          pid: 1,
          state: "ready"
        })

      assert {:error, :malformed} = Identity.parse_metadata(raw)
    end

    test "rejects out-of-range pid" do
      raw = Jason.encode!(%{version: 1, node: @node, host: "127.0.0.1", pid: -1, state: "ready"})
      assert {:error, :malformed} = Identity.parse_metadata(raw)
    end

    test "rejects unknown state value" do
      raw = Jason.encode!(%{version: 1, node: @node, host: "127.0.0.1", pid: 1, state: "booting"})
      assert {:error, :malformed} = Identity.parse_metadata(raw)
    end

    test "round-trips through encode_metadata/1" do
      meta = %{node: @node, host: "127.0.0.1", pid: 55, state: :starting}
      assert {:ok, ^meta} = meta |> Identity.encode_metadata() |> Identity.parse_metadata()
    end
  end

  describe "validate_metadata_identity/2" do
    test "accepts a record whose id matches local_node_id and host matches its own suffix" do
      meta = %{node: @node, host: "127.0.0.1", pid: 1, state: :ready}
      assert :ok = Identity.validate_metadata_identity(meta, @local_id)
    end

    test "rejects a record generated by a different machine's node_id" do
      meta = %{node: @node, host: "127.0.0.1", pid: 1, state: :ready}
      assert {:error, :malformed} = Identity.validate_metadata_identity(meta, "ffff")
    end

    test "rejects self-inconsistent node/host fields" do
      meta = %{node: @node, host: "10.42.42.103", pid: 1, state: :ready}
      assert {:error, :malformed} = Identity.validate_metadata_identity(meta, @local_id)
    end
  end

  # -- lock owner parsing + decide_lock_step --------------------------------

  describe "lock owner parsing" do
    test "round-trips" do
      raw = Identity.encode_lock_owner(999, "tok")
      assert {:ok, %{pid: 999, token: "tok"}} = Identity.parse_lock_owner(raw)
    end

    test "rejects oversized owner records" do
      raw = Jason.encode!(%{pid: 1, token: String.duplicate("a", 1000)})
      assert {:error, :malformed} = Identity.parse_lock_owner(raw)
    end

    test "rejects non-JSON" do
      assert {:error, :malformed} = Identity.parse_lock_owner("garbage")
    end
  end

  describe "decide_lock_step/1" do
    test "refuses when the owner is verified alive" do
      assert {:refuse, :held_by, 999} =
               Identity.decide_lock_step(%{
                 owner: {:ok, %{pid: 999, token: "t"}},
                 owner_pid_alive?: true
               })
    end

    test "refuses a stale owner for explicit manual recovery" do
      assert {:refuse, :stale_lock, %{pid: 999}} =
               Identity.decide_lock_step(%{
                 owner: {:ok, %{pid: 999, token: "t"}},
                 owner_pid_alive?: false
               })
    end

    test "refuses ambiguously when owner liveness cannot be determined" do
      assert {:refuse, :ambiguous_lock, %{}} =
               Identity.decide_lock_step(%{
                 owner: {:ok, %{pid: 999, token: "t"}},
                 owner_pid_alive?: :unverified
               })
    end

    test "refuses ambiguously on a malformed owner record" do
      assert {:refuse, :ambiguous_lock, %{}} =
               Identity.decide_lock_step(%{
                 owner: {:error, :malformed},
                 owner_pid_alive?: :unverified
               })
    end

    test "refuses ambiguously when the owner record is absent (mkdir raced us out)" do
      assert {:refuse, :ambiguous_lock, %{}} =
               Identity.decide_lock_step(%{owner: :absent, owner_pid_alive?: :unverified})
    end
  end

  # -- parse_arbor_node_from_argv -------------------------------------------

  describe "parse_arbor_node_from_argv/2" do
    test "recognizes the erl-reexec single-dash -name form (the real macOS ps shape)" do
      argv =
        "/usr/local/bin/erl -name #{@node} -cookie secretcookievalue -kernel inet_dist_listen_min 9100"

      assert {:verified_arbor, @node} = Identity.parse_arbor_node_from_argv(argv, @local_id)
    end

    test "recognizes the elixir launcher double-dash --name form" do
      argv = "elixir --name #{@node} --cookie secretcookievalue -S mix run --no-halt"
      assert {:verified_arbor, @node} = Identity.parse_arbor_node_from_argv(argv, @local_id)
    end

    test "recognizes single-dash -sname" do
      argv = "erl -sname #{@node} -cookie x"
      assert {:verified_arbor, @node} = Identity.parse_arbor_node_from_argv(argv, @local_id)
    end

    test "rejects when the id prefix does not match the local node_id (pid reuse / foreign node)" do
      argv = "erl -name #{@foreign_node} -cookie x"
      assert :present_not_arbor = Identity.parse_arbor_node_from_argv(argv, @local_id)
    end

    test "rejects an unrelated process's argv with no name flag at all" do
      argv = "/usr/sbin/cupsd -l"
      assert :present_not_arbor = Identity.parse_arbor_node_from_argv(argv, @local_id)
    end

    test "never surfaces the adjacent cookie value in its result" do
      argv = "erl -name #{@node} -cookie topsecretcookie123"
      assert {:verified_arbor, node} = Identity.parse_arbor_node_from_argv(argv, @local_id)
      refute node =~ "topsecretcookie123"
      refute inspect(Identity.parse_arbor_node_from_argv(argv, @local_id)) =~ "topsecretcookie123"
    end
  end

  # -- decide_start/1 (behavior matrix) -------------------------------------

  defp host_intent(tag \\ :auto, host \\ "127.0.0.1"), do: {tag, host}

  describe "decide_start/1" do
    test "fresh install: no metadata, no legacy pid -> proceed" do
      facts = %{metadata: :absent, legacy_pid_present?: false, host_intent: host_intent()}
      assert {:proceed, "127.0.0.1"} = Identity.decide_start(facts)
    end

    test "legacy daemon verified alive -> refuses (legacy daemons block start)" do
      facts = %{
        metadata: :absent,
        legacy_pid_present?: true,
        legacy_pid_check: {:verified_arbor, @node},
        host_intent: host_intent()
      }

      assert {:refuse, :legacy_daemon_alive, %{node: @node}} = Identity.decide_start(facts)
    end

    test "legacy pid stale (dead) -> proceeds" do
      facts = %{
        metadata: :absent,
        legacy_pid_present?: true,
        legacy_pid_check: :no_such_process,
        host_intent: host_intent()
      }

      assert {:proceed, "127.0.0.1"} = Identity.decide_start(facts)
    end

    test "legacy pid reused by an unrelated process -> proceeds" do
      facts = %{
        metadata: :absent,
        legacy_pid_present?: true,
        legacy_pid_check: :present_not_arbor,
        host_intent: host_intent()
      }

      assert {:proceed, "127.0.0.1"} = Identity.decide_start(facts)
    end

    test "legacy pid liveness unverified -> refuses ambiguously" do
      facts = %{
        metadata: :absent,
        legacy_pid_present?: true,
        legacy_pid_check: :unverified,
        host_intent: host_intent()
      }

      assert {:refuse, :ambiguous_legacy_state, %{}} = Identity.decide_start(facts)
    end

    test "malformed metadata -> refuses and never proceeds (never treated as absent)" do
      facts = %{metadata: {:error, :malformed}, host_intent: host_intent()}
      assert {:refuse, :malformed_metadata, %{}} = Identity.decide_start(facts)
    end

    test "valid metadata, pid verified match -> refuses already_running" do
      meta = %{node: @node, host: "127.0.0.1", pid: 42, state: :ready}

      facts = %{
        metadata: {:ok, meta},
        metadata_pid_check: {:verified_arbor, @node},
        host_intent: host_intent()
      }

      assert {:refuse, :already_running, %{node: @node, pid: 42}} = Identity.decide_start(facts)
    end

    test "valid metadata, pid verified but names a different node -> refuses node_identity_mismatch" do
      meta = %{node: @node, host: "127.0.0.1", pid: 42, state: :ready}

      facts = %{
        metadata: {:ok, meta},
        metadata_pid_check: {:verified_arbor, @other_node},
        host_intent: host_intent()
      }

      assert {:refuse, :node_identity_mismatch, %{expected: @node, observed: @other_node}} =
               Identity.decide_start(facts)
    end

    test "valid metadata, pid ambiguous -> refuses ambiguous_metadata_pid" do
      meta = %{node: @node, host: "127.0.0.1", pid: 42, state: :ready}

      facts = %{
        metadata: {:ok, meta},
        metadata_pid_check: :unverified,
        host_intent: host_intent()
      }

      assert {:refuse, :ambiguous_metadata_pid, %{}} = Identity.decide_start(facts)
    end

    test "valid metadata, pid stale -> proceeds (stale metadata safe to overwrite)" do
      meta = %{node: @node, host: "127.0.0.1", pid: 42, state: :ready}

      facts = %{
        metadata: {:ok, meta},
        metadata_pid_check: :no_such_process,
        host_intent: host_intent(:auto, "10.42.42.103")
      }

      assert {:proceed, "10.42.42.103"} = Identity.decide_start(facts)
    end

    test "host drift without an explicit override, persisted node verified alive -> refuses (the incident)" do
      # Reproduces the reported incident directly: metadata was written for
      # 127.0.0.1, the interface-detected host has since drifted to
      # 10.42.42.103, and no operator override is set. Naively recomputing
      # the node from the freshly detected host (the pre-fix behavior) would
      # never even ask this question; here the persisted node is checked and
      # found verified-alive, so start refuses instead of spawning a
      # duplicate.
      meta = %{node: @node, host: "127.0.0.1", pid: 42, state: :ready}

      facts = %{
        metadata: {:ok, meta},
        metadata_pid_check: {:verified_arbor, @node},
        host_intent: host_intent(:auto, "10.42.42.103")
      }

      assert {:refuse, :already_running, _} = Identity.decide_start(facts)
    end

    test "explicit relocation while the old host is verified alive -> refuses (must stop first)" do
      meta = %{node: @node, host: "127.0.0.1", pid: 42, state: :ready}

      facts = %{
        metadata: {:ok, meta},
        metadata_pid_check: {:verified_arbor, @node},
        host_intent: host_intent(:operator_relocation, "10.42.42.103")
      }

      assert {:refuse, :already_running, _} = Identity.decide_start(facts)
    end

    test "explicit relocation once the old host is confirmed dead -> proceeds at the new host" do
      meta = %{node: @node, host: "127.0.0.1", pid: 42, state: :ready}

      facts = %{
        metadata: {:ok, meta},
        metadata_pid_check: :no_such_process,
        host_intent: host_intent(:operator_relocation, "10.42.42.103")
      }

      assert {:proceed, "10.42.42.103"} = Identity.decide_start(facts)
    end

    test "restart continuity host is honored when no operator override is present" do
      facts = %{
        metadata: :absent,
        legacy_pid_present?: false,
        host_intent: host_intent(:internal_continuity, "127.0.0.1")
      }

      assert {:proceed, "127.0.0.1"} = Identity.decide_start(facts)
    end
  end

  # -- decide_stop/1 (behavior matrix) --------------------------------------

  describe "decide_stop/1" do
    test "verified match, node reachable -> stop_via_verified with RPC attempt" do
      meta = %{node: @node, host: "127.0.0.1", pid: 42, state: :ready}

      facts = %{
        metadata: {:ok, meta},
        metadata_pid_check: {:verified_arbor, @node},
        node_ping: :pong
      }

      assert {:stop_via_verified, @node, 42, true} = Identity.decide_stop(facts)
    end

    test "verified match, node unreachable -> stop_via_verified without RPC attempt" do
      meta = %{node: @node, host: "127.0.0.1", pid: 42, state: :starting}

      facts = %{
        metadata: {:ok, meta},
        metadata_pid_check: {:verified_arbor, @node},
        node_ping: :pang
      }

      assert {:stop_via_verified, @node, 42, false} = Identity.decide_stop(facts)
    end

    test "node identity mismatch -> ambiguous, never signals" do
      meta = %{node: @node, host: "127.0.0.1", pid: 42, state: :ready}
      facts = %{metadata: {:ok, meta}, metadata_pid_check: {:verified_arbor, @other_node}}
      assert {:ambiguous, %{reason: :node_identity_mismatch}} = Identity.decide_stop(facts)
    end

    test "pid unverified -> ambiguous, never signals" do
      meta = %{node: @node, host: "127.0.0.1", pid: 42, state: :ready}
      facts = %{metadata: {:ok, meta}, metadata_pid_check: :unverified}
      assert {:ambiguous, %{reason: :ambiguous_metadata_pid}} = Identity.decide_stop(facts)
    end

    test "metadata stale (dead pid) -> already_stopped, cleans up both files" do
      meta = %{node: @node, host: "127.0.0.1", pid: 42, state: :ready}
      facts = %{metadata: {:ok, meta}, metadata_pid_check: :no_such_process}
      assert {:already_stopped, [:pid_file, :metadata_file]} = Identity.decide_stop(facts)
    end

    test "metadata pid reused -> already_stopped, cleans up both files" do
      meta = %{node: @node, host: "127.0.0.1", pid: 42, state: :ready}
      facts = %{metadata: {:ok, meta}, metadata_pid_check: :present_not_arbor}
      assert {:already_stopped, [:pid_file, :metadata_file]} = Identity.decide_stop(facts)
    end

    test "security regression: malformed canonical metadata is ambiguous, never falls back to legacy or already_stopped" do
      # Canonical metadata exists but is corrupted -- distinct from :absent.
      # A prior version of this decision treated {:error, :malformed} the
      # same as :absent and fell through to the legacy-PID branch, which
      # could report already_stopped (silently green-lighting Restart to
      # launch a second daemon) or signal an unrelated legacy PID while a
      # real canonically-tracked daemon might still be alive. Even a legacy
      # PID that verifies as alive must not override this: malformed
      # canonical evidence is ambiguous on its own.
      facts = %{
        metadata: {:error, :malformed},
        legacy_pid_present?: true,
        legacy_pid: 77,
        legacy_pid_check: {:verified_arbor, @node},
        node_ping: :pang
      }

      assert {:ambiguous, %{reason: :malformed_canonical_metadata}} = Identity.decide_stop(facts)
    end

    test "malformed canonical metadata, no legacy pid -> still ambiguous, never already_stopped" do
      facts = %{metadata: {:error, :malformed}, legacy_pid_present?: false}
      assert {:ambiguous, %{reason: :malformed_canonical_metadata}} = Identity.decide_stop(facts)
    end

    test "absent metadata, legacy stale -> already_stopped, cleans up only the pid file" do
      facts = %{
        metadata: :absent,
        legacy_pid_present?: true,
        legacy_pid: 77,
        legacy_pid_check: :no_such_process
      }

      assert {:already_stopped, [:pid_file]} = Identity.decide_stop(facts)
    end

    test "absent metadata, legacy unverified -> ambiguous, never signals" do
      facts = %{
        metadata: :absent,
        legacy_pid_present?: true,
        legacy_pid: 77,
        legacy_pid_check: :unverified
      }

      assert {:ambiguous, %{reason: :ambiguous_legacy_state}} = Identity.decide_stop(facts)
    end

    test "absent metadata, no legacy pid -> already_stopped, nothing to clean up" do
      facts = %{metadata: :absent, legacy_pid_present?: false}
      assert {:already_stopped, []} = Identity.decide_stop(facts)
    end
  end

  # -- decide_signal_authorization/2 ----------------------------------------

  describe "decide_signal_authorization/2" do
    test "verified match against the expected node -> safe_to_signal" do
      assert :safe_to_signal =
               Identity.decide_signal_authorization({:verified_arbor, @node}, @node)
    end

    test "verified but a different node -> preserve_evidence" do
      assert :preserve_evidence =
               Identity.decide_signal_authorization({:verified_arbor, @other_node}, @node)
    end

    test "unverified -> preserve_evidence" do
      assert :preserve_evidence = Identity.decide_signal_authorization(:unverified, @node)
    end

    test "no such process -> preserve_evidence" do
      assert :preserve_evidence = Identity.decide_signal_authorization(:no_such_process, @node)
    end

    test "present but not arbor -> preserve_evidence" do
      assert :preserve_evidence = Identity.decide_signal_authorization(:present_not_arbor, @node)
    end
  end

  # -- decide_stop_confirmation/1 -------------------------------------------

  describe "decide_stop_confirmation/1" do
    test "node unreachable and OS exit confirmed -> confirmed_stopped" do
      assert :confirmed_stopped =
               Identity.decide_stop_confirmation(%{node_unreachable?: true, os_exited?: true})
    end

    test "security regression: node unreachable does not by itself confirm OS process exit" do
      # Distributed-Erlang unreachability (a partition, an EPMD hiccup,
      # net_ticktime expiry) is not proof the OS process exited. Before this
      # fix, Stop's poll_until_stopped/2 declared a clean stop from
      # node_alive?/1 == false alone and deleted tracking state on that
      # basis — this exact fact combination has no such gate on the
      # reconstructed checkpoint (this function doesn't exist there) and
      # would have to be treated as a confirmed stop for the bug to persist.
      assert :escalate_to_signal =
               Identity.decide_stop_confirmation(%{node_unreachable?: true, os_exited?: false})
    end

    test "node still reachable, OS exit not observed -> escalate_to_signal" do
      assert :escalate_to_signal =
               Identity.decide_stop_confirmation(%{node_unreachable?: false, os_exited?: false})
    end

    test "node still reachable even if OS exit was somehow reported -> escalate_to_signal" do
      assert :escalate_to_signal =
               Identity.decide_stop_confirmation(%{node_unreachable?: false, os_exited?: true})
    end
  end

  # -- decide_status/1 ------------------------------------------------------

  describe "decide_status/1" do
    test "canonical metadata requires an exact node identity match" do
      meta = %{node: @node, host: "127.0.0.1", pid: 42, state: :ready}

      assert {:managed, @node, 42} =
               Identity.decide_status(%{
                 metadata: {:ok, meta},
                 metadata_pid_check: {:verified_arbor, @node}
               })

      assert :ambiguous =
               Identity.decide_status(%{
                 metadata: {:ok, meta},
                 metadata_pid_check: {:verified_arbor, @other_node}
               })
    end

    test "canonical metadata never falls back to a conflicting legacy identity" do
      meta = %{node: @node, host: "127.0.0.1", pid: 42, state: :ready}

      assert :none =
               Identity.decide_status(%{
                 metadata: {:ok, meta},
                 metadata_pid_check: :no_such_process,
                 legacy_pid_present?: true,
                 legacy_pid: 77,
                 legacy_pid_check: {:verified_arbor, @other_node}
               })
    end

    test "legacy identity is used only when canonical metadata is absent" do
      assert {:managed, @node, 77} =
               Identity.decide_status(%{
                 metadata: :absent,
                 legacy_pid_present?: true,
                 legacy_pid: 77,
                 legacy_pid_check: {:verified_arbor, @node}
               })
    end

    test "malformed canonical metadata remains ambiguous" do
      assert :ambiguous =
               Identity.decide_status(%{
                 metadata: {:error, :malformed},
                 legacy_pid_present?: false
               })
    end
  end

  # -- Helpers.signal_if_verified/3 boundary regression ---------------------

  describe "Helpers.signal_if_verified/3 boundary regression" do
    test "an alive, non-Arbor pid is revalidated and refused -- never signaled, still alive after" do
      pid = self_pid()

      assert {:refused, check} = Config.signal_if_verified(pid, @foreign_node, :sigterm)
      refute match?({:verified_arbor, _}, check)

      # The literal proof required: a real, alive, non-Arbor process, still
      # alive immediately after the call that could have signaled it.
      assert Config.pid_alive?(pid)
    end
  end

  # -- Helpers.acquire_lock/1 stale-lock fail-closed behavior ----------------

  describe "Helpers.acquire_lock/1 stale-lock fail-closed behavior" do
    # Linux's largest configurable pid_max is 4_194_304 (the value itself is
    # not allocated), while Darwin's limit is lower. This remains inside the
    # lifecycle record's accepted bound but cannot identify a live process.
    @dead_pid 4_194_304

    defp stage_stale_lock(home) do
      refute Config.pid_alive?(@dead_pid)

      dir = Config.lock_dir(home)
      File.mkdir_p!(dir)

      File.write!(
        Path.join(dir, "owner.json"),
        Identity.encode_lock_owner(@dead_pid, "stale-token")
      )

      dir
    end

    test "security regression: a delayed stale contender cannot remove a replacement lock" do
      home = tmp_home()
      dir = stage_stale_lock(home)

      assert {:refuse, :stale_lock, %{pid: @dead_pid}} = Config.acquire_lock(home)
      assert File.dir?(dir)

      # Simulate explicit operator recovery, then a new command acquiring a
      # fresh generation. A delayed contender has no stale-reclaim primitive
      # to invoke: it must re-observe the live owner and leave the token intact.
      File.rm_rf!(dir)
      assert {:ok, token} = Config.acquire_lock(home)
      owner_before = File.read!(Path.join(dir, "owner.json"))

      assert {:refuse, :held_by, _pid} = Config.acquire_lock(home)
      assert File.read!(Path.join(dir, "owner.json")) == owner_before

      Config.release_lock(home, token)
    end

    test "concurrent acquire_lock/1 contenders on a fresh path -- never more than one holder" do
      home = tmp_home()

      results =
        1..16
        |> Enum.map(fn _ -> Task.async(fn -> Config.acquire_lock(home) end) end)
        |> Enum.map(&Task.await(&1, 10_000))

      successes = Enum.filter(results, &match?({:ok, _token}, &1))

      assert length(successes) == 1

      case successes do
        [{:ok, token}] -> Config.release_lock(home, token)
        [] -> :ok
      end
    end
  end

  # -- Helpers.read_pid/1 and read_metadata/1 boundary reads ----------------

  describe "Helpers.read_pid/1 and read_metadata/1 boundary reads" do
    test "read_pid/1: absent file -> :absent" do
      assert :absent = Config.read_pid(tmp_home())
    end

    test "read_pid/1: non-numeric content -> {:error, :malformed}" do
      home = tmp_home()
      File.write!(Config.pid_file(home), "not-a-pid")
      assert {:error, :malformed} = Config.read_pid(home)
    end

    test "read_pid/1: a directory in place of the file -> {:error, :malformed}" do
      home = tmp_home()
      File.mkdir_p!(Config.pid_file(home))
      assert {:error, :malformed} = Config.read_pid(home)
    end

    test "read_pid/1: well-formed content -> {:ok, pid}" do
      home = tmp_home()
      File.write!(Config.pid_file(home), "4242")
      assert {:ok, 4242} = Config.read_pid(home)
    end

    test "read_metadata/1: absent file -> :absent" do
      assert :absent = Config.read_metadata(tmp_home())
    end

    test "read_metadata/1: malformed JSON -> {:error, :malformed}" do
      home = tmp_home()
      File.write!(Config.metadata_file(home), "not json")
      assert {:error, :malformed} = Config.read_metadata(home)
    end

    test "read_metadata/1: a directory in place of the file -> {:error, :malformed}" do
      home = tmp_home()
      File.mkdir_p!(Config.metadata_file(home))
      assert {:error, :malformed} = Config.read_metadata(home)
    end
  end

  # -- Start.track_launch/4 tracking-transaction regressions ----------------

  describe "Start.track_launch/4 tracking-transaction regressions" do
    test "legacy write fails, metadata succeeds -> :ok, warns visibly, canonical evidence present, nothing signaled" do
      home = tmp_home()
      pid = self_pid()
      # A validly-shaped node string (real local node_id, so it round-trips
      # through read_metadata's identity cross-check) -- unlike @foreign_node,
      # which is deliberately shape-invalid for the argv-parsing tests above.
      node_string = "arbor_dev_#{Config.node_id()}@127.0.0.1"
      # Force the legacy pid-file write to fail: a directory sits where the
      # pid file must be written.
      File.mkdir_p!(Config.pid_file(home))

      stderr =
        ExUnit.CaptureIO.capture_io(:stderr, fn ->
          assert :ok = Start.track_launch(node_string, "127.0.0.1", pid, home)
        end)

      # Operator-visible warning required: a legacy-write failure tolerated
      # because canonical metadata succeeded must never be silent -- the
      # operator needs to know legacy-only fallback tooling has nothing to
      # find for this daemon.
      assert stderr =~ "Warning: failed to write the legacy PID file"
      assert stderr =~ Config.pid_file(home)

      assert {:ok, %{node: ^node_string}} = Config.read_metadata(home)
      assert {:error, :malformed} = Config.read_pid(home)
      assert Config.pid_alive?(pid)
    end

    test "metadata write fails, legacy evidence preserved -> signal_if_verified invoked and refused, exits" do
      home = tmp_home()
      pid = self_pid()
      # Force the metadata write to fail: a directory sits where
      # write_metadata!/2's File.rename! must land.
      File.mkdir_p!(Config.metadata_file(home))

      assert catch_exit(Start.track_launch(@foreign_node, "127.0.0.1", pid, home)) ==
               {:shutdown, 1}

      assert {:ok, ^pid} = Config.read_pid(home)
      assert Config.pid_alive?(pid)
    end

    test "dual write failure -> no evidence exists, signal_if_verified invoked and refused, exits" do
      home = tmp_home()
      pid = self_pid()
      File.mkdir_p!(Config.pid_file(home))
      File.mkdir_p!(Config.metadata_file(home))

      assert catch_exit(Start.track_launch(@foreign_node, "127.0.0.1", pid, home)) ==
               {:shutdown, 1}

      assert {:error, :malformed} = Config.read_pid(home)
      assert {:error, :malformed} = Config.read_metadata(home)
      assert Config.pid_alive?(pid)
    end
  end

  # -- Restart.capture_persisted_host/1 --------------------------------------

  describe "Restart.capture_persisted_host/1" do
    test "well-formed legacy pid file -> no crash (finding #1 regression)" do
      home = tmp_home()
      File.write!(Config.pid_file(home), to_string(self_pid()))

      # The tagged read_pid/1 contract (:absent | {:ok, pid} | {:error,
      # :malformed}) previously crashed here via Protocol.UndefinedError on
      # to_string/1 of a tuple. Reaching an assertion at all is the fix.
      assert is_nil(Restart.capture_persisted_host(home))
    end

    test "malformed legacy pid file -> nil, no crash" do
      home = tmp_home()
      File.write!(Config.pid_file(home), "not-a-pid")

      assert is_nil(Restart.capture_persisted_host(home))
    end

    test "malformed metadata -> nil, no crash" do
      home = tmp_home()
      File.write!(Config.metadata_file(home), "not json")

      assert is_nil(Restart.capture_persisted_host(home))
    end

    test "no tracking state -> nil" do
      assert is_nil(Restart.capture_persisted_host(tmp_home()))
    end
  end

  # -- Status.resolve_managed_node/1 -----------------------------------------

  describe "Status.resolve_managed_node/1" do
    test "well-formed legacy pid file, not verified as arbor -> :none, no crash (finding #1 regression)" do
      home = tmp_home()
      File.write!(Config.pid_file(home), to_string(self_pid()))

      assert :none = Status.resolve_managed_node(home)
    end

    test "malformed legacy pid file -> :ambiguous, never silently :none" do
      home = tmp_home()
      File.write!(Config.pid_file(home), "not-a-pid")

      assert :ambiguous = Status.resolve_managed_node(home)
    end

    test "malformed metadata -> :ambiguous" do
      home = tmp_home()
      File.write!(Config.metadata_file(home), "not json")

      assert :ambiguous = Status.resolve_managed_node(home)
    end

    test "no tracking state -> :none" do
      assert :none = Status.resolve_managed_node(tmp_home())
    end
  end
end
