defmodule Arbor.Security.SessionToken do
  @moduledoc """
  Signed session tokens for human identity verification.

  When a human authenticates via OIDC, a session token is generated and
  signed by the SystemAuthority. This token proves that a LiveView process
  or API call was initiated by an authenticated human, without requiring
  per-call Ed25519 signing (which agents use).

  ## Token Format

  The token is a signed map containing:
  - `principal_id` — the human's `human_<hash>` identity
  - `session_id` — unique session identifier
  - `issued_at` — when the token was created
  - `expires_at` — when the token expires (default: 24 hours)

  ## Usage

      # Generate during OIDC callback
      {:ok, token} = SessionToken.generate("human_abc123")

      # Verify in authorize calls
      {:ok, principal_id} = SessionToken.verify(token)

      # Pass to Security.authorize
      Security.authorize(principal_id, resource, action, session_token: token)
  """

  require Logger

  @default_ttl_seconds 86_400
  @token_version 1

  @doc """
  Generate a signed session token for a human principal.
  """
  @spec generate(String.t(), keyword()) :: {:ok, binary()} | {:error, term()}
  def generate(principal_id, opts \\ []) when is_binary(principal_id) do
    ttl = Keyword.get(opts, :ttl, @default_ttl_seconds)
    now = DateTime.utc_now()
    expires_at = DateTime.add(now, ttl, :second)
    session_id = Keyword.get(opts, :session_id, generate_session_id())

    payload = %{
      v: @token_version,
      pid: principal_id,
      sid: session_id,
      iat: DateTime.to_unix(now),
      exp: DateTime.to_unix(expires_at)
    }

    {:ok, signature} = sign_payload(payload)

    token =
      %{payload: payload, sig: signature}
      |> :erlang.term_to_binary()
      |> Base.url_encode64(padding: false)

    {:ok, token}
  end

  @doc """
  Verify a session token and return the principal_id if valid.
  """
  @spec verify(binary()) :: {:ok, String.t()} | {:error, term()}
  def verify(token) when is_binary(token) do
    with {:ok, decoded} <- decode_token(token),
         :ok <- check_version(decoded.payload),
         :ok <- check_expiry(decoded.payload),
         :ok <- verify_signature(decoded.payload, decoded.sig) do
      {:ok, decoded.payload.pid}
    end
  end

  def verify(_), do: {:error, :invalid_token}

  @doc """
  Check if a value is a valid session token (without full verification).
  """
  @spec token?(term()) :: boolean()
  def token?(token) when is_binary(token) and byte_size(token) > 20, do: true
  def token?(_), do: false

  # --- Private ---

  defp decode_token(token) do
    case Base.url_decode64(token, padding: false) do
      {:ok, binary} ->
        try do
          # Safe: tokens are generated by our own system, not from user input
          term = :erlang.binary_to_term(binary, [:safe])

          case term do
            %{payload: %{v: _, pid: _, sid: _, iat: _, exp: _} = payload, sig: sig} ->
              {:ok, %{payload: payload, sig: sig}}

            _ ->
              {:error, :malformed_token}
          end
        rescue
          _ -> {:error, :invalid_binary}
        end

      :error ->
        {:error, :invalid_base64}
    end
  end

  defp check_version(%{v: @token_version}), do: :ok
  defp check_version(%{v: v}), do: {:error, {:unsupported_version, v}}

  defp check_expiry(%{exp: exp}) do
    now = DateTime.to_unix(DateTime.utc_now())

    if now < exp do
      :ok
    else
      {:error, :token_expired}
    end
  end

  defp sign_payload(payload) do
    payload_binary = :erlang.term_to_binary(payload)
    secret = token_secret()
    signature = :crypto.mac(:hmac, :sha256, secret, payload_binary)
    {:ok, signature}
  end

  defp verify_signature(payload, signature) do
    payload_binary = :erlang.term_to_binary(payload)
    secret = token_secret()
    expected = :crypto.mac(:hmac, :sha256, secret, payload_binary)

    if secure_compare(expected, signature) do
      :ok
    else
      {:error, :invalid_signature}
    end
  end

  defp token_secret do
    Application.get_env(:arbor_security, :session_token_secret) ||
      raise "session_token_secret not configured — set config :arbor_security, :session_token_secret"
  end

  # Constant-time comparison to prevent timing attacks
  defp secure_compare(a, b) when byte_size(a) == byte_size(b) do
    :crypto.hash_equals(a, b)
  end

  defp secure_compare(_, _), do: false

  defp generate_session_id do
    :crypto.strong_rand_bytes(16) |> Base.encode16(case: :lower)
  end
end
