defmodule Arbor.Persistence.MigrationHelper do
  @moduledoc """
  Helper functions for writing adapter-aware Ecto migrations.

  Provides `postgres?/0` and `sqlite?/0` checks plus adapter-aware
  SQL fragment helpers so migrations work on both PostgreSQL and SQLite.

  ## Usage

      defmodule MyMigration do
        use Ecto.Migration
        import Arbor.Persistence.MigrationHelper

        def change do
          create table(:things) do
            add :created_at, :utc_datetime_usec, null: false, default: now_fragment()
          end

          if postgres?() do
            create index(:things, [:data], using: "GIN")
          end
        end
      end
  """

  @doc "Returns true if the current repo uses the Postgres adapter."
  def postgres? do
    # Use Application.get_env at runtime to avoid compile-time type warnings
    # from the Elixir compiler (which knows the concrete adapter type).
    Application.get_env(:arbor_persistence, :repo_adapter, Ecto.Adapters.Postgres) ==
      Ecto.Adapters.Postgres
  end

  @doc "Returns true if the current repo uses the SQLite3 adapter."
  def sqlite? do
    not postgres?()
  end

  @doc "Returns a NOW() fragment appropriate for the current adapter."
  defmacro now_fragment do
    quote do
      if Arbor.Persistence.MigrationHelper.postgres?() do
        fragment("NOW()")
      else
        # SQLite requires expression defaults wrapped in parens
        fragment("(datetime('now'))")
      end
    end
  end

  @doc "Returns a gen_random_uuid() fragment for Postgres, nil for SQLite (use Ecto.UUID)."
  defmacro uuid_default do
    quote do
      if Arbor.Persistence.MigrationHelper.postgres?() do
        fragment("gen_random_uuid()")
      else
        # SQLite: UUIDs generated by Ecto at insert time
        nil
      end
    end
  end

  @doc "Returns an empty JSON array fragment appropriate for the current adapter."
  defmacro empty_json_array do
    quote do
      if Arbor.Persistence.MigrationHelper.postgres?() do
        fragment("'[]'::jsonb")
      else
        fragment("'[]'")
      end
    end
  end
end
