defmodule Arbor.Actions.Tool.Help do
  @moduledoc """
  Get detailed documentation for a specific tool.

  Returns the tool's full parameter schema, description, category,
  tags, and usage examples. Use this when you know a tool's name
  but need to understand its parameters before calling it.

  ## Parameters

  | Name | Type | Required | Description |
  |------|------|----------|-------------|
  | `tool_name` | string | yes | Exact tool name (e.g., "file_read", "web_search") |
  """

  use Jido.Action,
    name: "tool_help",
    description:
      "Get detailed documentation for a specific tool. " <>
        "Returns parameter schema, description, and usage info. " <>
        "Use when you need to understand a tool's parameters before calling it.",
    category: "tool",
    tags: ["tool", "help", "documentation", "schema"],
    schema: [
      tool_name: [type: :string, required: true, doc: "Tool name (e.g., 'file_read', 'shell_execute')"]
    ]

  require Logger

  @impl true
  def run(params, _context) do
    tool_name = params[:tool_name]

    case resolve_tool(tool_name) do
      {:ok, module, spec} ->
        {:ok, format_help(tool_name, module, spec)}

      {:error, :not_found} ->
        {:ok, %{
          error: "Tool '#{tool_name}' not found.",
          suggestion: "Use tool_find_tools to search for available tools."
        }}
    end
  end

  defp resolve_tool(name) do
    registry = Arbor.Common.ActionRegistry

    if Code.ensure_loaded?(registry) and function_exported?(registry, :resolve_by_name, 1) do
      # Try canonical (dot) format first, then underscore
      case apply(registry, :resolve_by_name, [name]) do
        {:ok, module} -> get_spec(module)
        {:error, _} ->
          # Try alternate format
          alt = if String.contains?(name, "."), do: String.replace(name, ".", "_"), else: String.replace(name, "_", ".")
          case apply(registry, :resolve_by_name, [alt]) do
            {:ok, module} -> get_spec(module)
            {:error, _} -> {:error, :not_found}
          end
      end
    else
      {:error, :not_found}
    end
  end

  defp get_spec(module) do
    # to_tool/0 is generated by Jido.Action macro — function_exported? returns
    # false for it, but it's callable. Use try/rescue instead.
    spec = module.to_tool()
    {:ok, module, spec}
  rescue
    _ -> {:error, :not_found}
  end

  defp format_help(tool_name, module, spec) do
    params = spec[:parameters_schema] || %{}
    properties = params["properties"] || %{}
    required = params["required"] || []

    # Build parameter table
    param_docs =
      properties
      |> Enum.sort_by(fn {name, _} -> name end)
      |> Enum.map(fn {name, schema} ->
        type = schema["type"] || "any"
        desc = schema["description"] || ""
        req = if name in required, do: "required", else: "optional"
        default = if schema["default"], do: " (default: #{inspect(schema["default"])})", else: ""
        enum = if schema["enum"], do: " [#{Enum.join(schema["enum"], ", ")}]", else: ""

        "  #{name} (#{type}, #{req}#{default}#{enum}): #{desc}"
      end)
      |> Enum.join("\n")

    # Build category/tags info
    category = get_category(module)
    tags = get_tags(module)

    %{
      name: tool_name,
      description: spec[:description] || "",
      parameters: param_docs,
      required: required,
      category: category,
      tags: tags,
      module: inspect(module)
    }
  end

  defp get_category(module) do
    if function_exported?(module, :category, 0), do: module.category(), else: nil
  rescue
    _ -> nil
  end

  defp get_tags(module) do
    if function_exported?(module, :tags, 0), do: module.tags(), else: []
  rescue
    _ -> []
  end
end
